/*
 *   Copyright 2020-2026 Leon Latsch
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package dev.leonlatsch.photok.vaults.data.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

@Entity(tableName = VaultTable.TABLE_NAME)
data class VaultTable(
    @PrimaryKey
    @ColumnInfo(name = VAULT_UUID)
    val uuid: String = UUID.randomUUID().toString(),
    val name: String,
    val salt: ByteArray,
    val verifier: ByteArray,
    val iv: ByteArray,
) {
    companion object {
        const val TABLE_NAME = "vault"
        const val VAULT_UUID = "vault_uuid"
    }

    // Generated by AS. Re-generate if changing content. Needed because of arrays

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as VaultTable

        if (uuid != other.uuid) return false
        if (!salt.contentEquals(other.salt)) return false
        if (!verifier.contentEquals(other.verifier)) return false
        if (!iv.contentEquals(other.iv)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = uuid.hashCode()
        result = 31 * result + salt.contentHashCode()
        result = 31 * result + verifier.contentHashCode()
        result = 31 * result + iv.contentHashCode()
        return result
    }
}