name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Ruby + Fastlane
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Test
        run: bundle exec fastlane test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Ruby + Fastlane
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build
        run: bundle exec fastlane build
